#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          9
bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc rule -a Ulauncher state=floating border=off
bspc rule -a Ulauncher Preferences state=floating border=off

 bspc config focused_border_color        "#009dff"
 bspc config normal_border_color         "#000000"  
 bspc config presel_feedback_color	"#009dff"

$HOME/.config/polybar/launch.sh
bspwmrc
#nitrogen --restore &
/usr/bin/dunst &
picom &
/usr/bin/nitrogen --set-zoom-fill --random Pictures/Wallpapers --save
nm-applet &
blueman-applet &
touchegg &
