#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

 bspc config focused_border_color        "#d23793"
 #Green "#4CAF50"
 bspc config normal_border_color         "#00000000"  #"#C9846C"
 # bspc config active_border_color         "#C9846C"

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
$HOME/.config/polybar/shapes/launch.sh
# $HOME/.config/polybar/shapes/launch.sh
# bash ~/.config/polybar/launch.sh --shapes
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
xrandr --output eDP1 --scale 0.85x0.85
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

picom -CGb &
nm-applet --indicator &
xsetroot -cursor_name left_ptr &
