#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          9
bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc rule -a Ulauncher state=floating border=off
bspc rule -a Ulauncher Preferences state=floating border=off

 bspc config focused_border_color        "#009dff"
 bspc config normal_border_color         "#000000"  
 bspc config presel_feedback_color	"#009dff"

$HOME/.config/polybar/launch.sh
# $HOME/.config/polybar/shapes/launch.sh
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# nitrogen --restore &
/usr/bin/nitrogen --set-zoom-fill --random Pictures/Nice --save
xrandr --output eDP-1 --scale 0.9x0.9
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
picom -CGb &
nm-applet --indicator &
xsetroot -cursor_name left_ptr &
ulauncher &
